"""add avatar_url to users

Revision ID: 5ce63080868c
Revises: 313ef3a891a9
Create Date: 2026-03-21 22:34:09.849981

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ce63080868c"
down_revision: str | None = "313ef3a891a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("rag_documents_user_id_fkey"), "rag_documents", type_="foreignkey")
    op.drop_column("rag_documents", "user_id")
    op.add_column("users", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    op.add_column(
        "rag_documents", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("rag_documents_user_id_fkey"), "rag_documents", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
