"""add sync_logs table

Revision ID: 6e201ed8932c
Revises: 23d79001b5b8
Create Date: 2026-03-22 03:07:53.619615

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6e201ed8932c"
down_revision: str | None = "23d79001b5b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
