"""add missing indexes

Revision ID: 313ef3a891a9
Revises: fec1e50298cd
Create Date: 2026-03-20 17:15:29.826358

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "313ef3a891a9"
down_revision: str | None = "fec1e50298cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("sessions_user_id_idx"), "sessions", ["user_id"], unique=False)
    op.create_index(op.f("users_oauth_id_idx"), "users", ["oauth_id"], unique=False)
    op.create_index(op.f("users_oauth_provider_idx"), "users", ["oauth_provider"], unique=False)
    op.create_index(
        op.f("webhook_deliveries_created_at_idx"),
        "webhook_deliveries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("webhook_deliveries_webhook_id_idx"),
        "webhook_deliveries",
        ["webhook_id"],
        unique=False,
    )
    op.create_index(op.f("webhooks_user_id_idx"), "webhooks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("webhooks_user_id_idx"), table_name="webhooks")
    op.drop_index(op.f("webhook_deliveries_webhook_id_idx"), table_name="webhook_deliveries")
    op.drop_index(op.f("webhook_deliveries_created_at_idx"), table_name="webhook_deliveries")
    op.drop_index(op.f("users_oauth_provider_idx"), table_name="users")
    op.drop_index(op.f("users_oauth_id_idx"), table_name="users")
    op.drop_index(op.f("sessions_user_id_idx"), table_name="sessions")
    # ### end Alembic commands ###
